# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RRDTool-OO
version:      0.16
version_from: lib/RRDTool/OO.pm
installdirs:  site
requires:
    Log::Log4perl:                 0.40
    RRDs:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
